-- =====================================================================
-- V1: Schema khoi tao
--
-- Vi sao dung Flyway thay cho SchemaUtils.create()?
--   - SchemaUtils.create() chi TAO BANG NEU CHUA CO. No khong bao gio ALTER,
--     nen tu lan deploy thu hai tro di moi thay doi schema deu bi bo qua am tham.
--   - Flyway ghi lai tung phien ban da chay vao bang flyway_schema_history,
--     bao dam moi moi truong (dev/staging/prod) co cung schema, va co the
--     kiem tra lich su "ai doi gi, luc nao".
--
-- SQL o day co tinh viet theo chuan chung de chay duoc CA H2 (dev/test)
-- LAN PostgreSQL (production):
--   - "BIGINT GENERATED BY DEFAULT AS IDENTITY" la chuan SQL:2003, ca hai deu hieu.
--     (khong dung BIGSERIAL vi do la cu phap rieng cua PostgreSQL)
--   - "NUMERIC(12,2)" cho tien, khong dung DOUBLE.
-- =====================================================================

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(120) NOT NULL,
    phone         VARCHAR(20)  NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL
);

-- UNIQUE o tang DB la luoi an toan cuoi cung: du co race condition giua hai
-- request dang ky cung email thi DB van tu choi cai thu hai.
CREATE UNIQUE INDEX uq_users_email ON users (email);

CREATE TABLE vehicle_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    seats       INT          NOT NULL,
    description VARCHAR(255)
);

CREATE UNIQUE INDEX uq_vehicle_types_name ON vehicle_types (name);

CREATE TABLE vehicles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number  VARCHAR(20)   NOT NULL,
    brand         VARCHAR(60)   NOT NULL,
    model         VARCHAR(60)   NOT NULL,
    -- Khong dat ten cot la "year": day la tu khoa danh rieng trong H2 2.x
    -- (va nhieu DB khac), se gay loi cu phap. Dat ten ro nghia luon cho chac.
    manufacture_year INT        NOT NULL,
    type_id       BIGINT        NOT NULL,
    price_per_day NUMERIC(12,2) NOT NULL,
    status        VARCHAR(20)   NOT NULL,
    CONSTRAINT fk_vehicles_type FOREIGN KEY (type_id) REFERENCES vehicle_types (id)
);

CREATE UNIQUE INDEX uq_vehicles_plate_number ON vehicles (plate_number);
CREATE INDEX idx_vehicles_status ON vehicles (status);
CREATE INDEX idx_vehicles_type_id ON vehicles (type_id);

CREATE TABLE bookings (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT        NOT NULL,
    vehicle_id     BIGINT        NOT NULL,
    start_at       TIMESTAMP     NOT NULL,
    end_at         TIMESTAMP     NOT NULL,
    total_days     INT           NOT NULL,
    total_price    NUMERIC(12,2) NOT NULL,
    deposit_amount NUMERIC(12,2) NOT NULL,
    status         VARCHAR(20)   NOT NULL,
    note           VARCHAR(500),
    created_at     TIMESTAMP     NOT NULL,
    CONSTRAINT fk_bookings_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_bookings_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id),
    -- Chan du lieu vo nghia ngay tai tang DB, khong phu thuoc vao viec
    -- tang service co nho validate hay khong.
    CONSTRAINT ck_bookings_period CHECK (end_at > start_at)
);

-- Index phuc vu dung cau truy van hasOverlap(): loc theo xe + trang thai + khoang thoi gian.
CREATE INDEX idx_bookings_vehicle_status ON bookings (vehicle_id, status, start_at, end_at);
CREATE INDEX idx_bookings_user_id ON bookings (user_id);

-- =====================================================================
-- Refresh token
--
-- LUU Y BAO MAT: cot token_hash luu SHA-256 cua token, KHONG luu token goc.
-- Neu ke tan cong doc duoc database, ho cung khong the dung cac hash nay
-- de dang nhap - dung nguyen tac nhu luu mat khau.
-- =====================================================================
CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP   NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP   NOT NULL,
    user_agent VARCHAR(255),
    ip_address VARCHAR(64),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE UNIQUE INDEX uq_refresh_tokens_hash ON refresh_tokens (token_hash);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
